import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Craving",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex justify-between items-center">
          <h1>Craving</h1>
          <ul className="flex justify-center items-center gap-5">
            <li>Home</li>
            <li>About</li>
            <li>Blog</li>
            <li>Service</li>
            <li>dlsdlkds</li>
            <li>Consdtact</li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
